color0       #393A3D
color8       #909EA0
color1       #A18B6A
color9       #A18B6A
color2       #F96403
color10      #F96403
color3       #D9A13C
color11      #D9A13C
color4       #65B6EE
color12      #65B6EE
color5       #D4C7A1
color13      #D4C7A1
color6       #AED5DB
color14      #AED5DB
color7       #CEE2E5
color15      #CEE2E5