color0       #413F45
color8       #949195
color1       #2687C3
color9       #2687C3
color2       #D47621
color10      #D47621
color3       #B889B6
color11      #B889B6
color4       #CE8C89
color12      #CE8C89
color5       #EBA418
color13      #EBA418
color6       #BAB1BD
color14      #BAB1BD
color7       #D4D0D6
color15      #D4D0D6