
## Hyprscroller - Scrolling Window Manager
#plugin=/home/arcius/.config/hypr/plugins/hyprscroller.so
plugin{
    scroller{
        column_widths = onethird onehalf twothirds one
        window_heights = onethird onehalf twothirds one

        focus_wrap = true
        cyclesize_wrap = true
        cyclewidth_wrap = true
        cycleheight_wrap = true
    }
}


